version: '3'

volumes:
  dados:

services:
  db:
    image: postgres:9.6
    container_name: db
    network_mode: bridge
    expose:
      - 5432
    ports:
      - 5432:5432
    volumes:
      - dados:/var/lib/postgresql/data
      - ./scripts:/scripts
      - ./scripts/init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      - POSTGRES_PASSWORD=123
      - POSTGRES_USER=postgres
      - POSTGRES_DB=minhasfinancas

  app:
    image: back-end
    build: .
    container_name: app
    network_mode: bridge
    ports:
      - 8080:8080
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db/minhasfinancas
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=123
    links:
      - db
    depends_on:
      - db


